  import { StyleSheet } from "react-native";

const COLORS = {
  primary: "#4A90E2",
  danger: "#E94E77",
  success: "#4CAF50",
  background: "#121212",
  text: "#FFFFFF",
  border: "#333333",
  white: "#FFFFFF",
  gray: "#888888",
  placeholder: "#AAAAAA",
};

const SPACING = {
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
};

const BORDER_RADIUS = {
  sm: 4,
  md: 8,
  lg: 12,
};

export const styles = StyleSheet.create({

  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  activitiesContainer: {
    padding: SPACING.md,
  },
  card: {
    flexDirection: "column", 
    padding: SPACING.md,
    marginBottom: SPACING.md,
    backgroundColor: "#252525",
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  cardText: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  cardButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: SPACING.sm,
    gap: SPACING.sm,
  },
  viewButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  editButton: {
    backgroundColor: "#0070F3",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteButton: {
    backgroundColor: COLORS.danger,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: "600",
  },
  addButton: {
    backgroundColor: COLORS.white,
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: 30,
    right: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  addButtonText: {
    color: "#000000",
    fontSize: 24,
    fontWeight: "bold",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "90%",
    backgroundColor: "#1E1E1E",
    padding: SPACING.lg,
    borderRadius: BORDER_RADIUS.md,
    maxHeight: "80%",
  },
  summaryTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.text,
    marginBottom: SPACING.md,
  },
  summaryDateTimeContainer: {
    marginBottom: SPACING.md,
  },
  summaryLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  summaryDateTime: {
    fontSize: 14,
    color: COLORS.text,
  },
  summaryScrollView: {
    maxHeight: 300,
  },
  summarySection: {
    marginBottom: SPACING.md,
  },
  summaryNoteContainer: {
    backgroundColor: "#252525",
    padding: SPACING.sm,
    borderRadius: BORDER_RADIUS.sm,
    marginBottom: SPACING.sm,
  },
  summaryNoteText: {
    fontSize: 14,
    color: COLORS.text,
  },
  summaryCloseButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.sm,
    alignItems: "center",
    marginTop: SPACING.md,
  },
  formScrollView: {
    paddingBottom: SPACING.lg,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.text,
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
  },
  input: {
    backgroundColor: "#252525",
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.md,
    color: COLORS.text,
    fontSize: 16,
  },
  pickerContainer: {
    flex: 1,
    backgroundColor: "#252525",
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginRight: SPACING.sm,
    overflow: "hidden",
  },
  pickerButton: {
    flex: 1,
    backgroundColor: "#333333",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.sm,
    alignItems: 'center',
    marginHorizontal: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  pickerButtonActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  pickerButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '500',
  },
  selectorScroll: {
    marginBottom: SPACING.md,
    maxHeight: 100,
  },
  selectorContainer: {
    backgroundColor: '#252525',
    borderRadius: BORDER_RADIUS.sm,
    marginBottom: SPACING.md,
    padding: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  selectorOption: {
    backgroundColor: '#333333',
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.sm,
    marginRight: SPACING.sm,
    minWidth: 60,
    alignItems: 'center',
  },
  selectorOptionSelected: {
    backgroundColor: COLORS.primary,
  },
  selectorOptionText: {
    color: COLORS.text,
    fontSize: 16,
  },
  selectorOptionTextSelected: {
    color: COLORS.white,
    fontWeight: 'bold',
  },
  formSection: {
    marginBottom: SPACING.lg,
  },
  formLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  formIcon: {
    marginRight: SPACING.sm,
  },
  removeNoteButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    zIndex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: SPACING.lg,
  },
  statCard: {
    backgroundColor: '#252525',
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    width: '48%', // for 2 cards per row
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  statIconContainer: {
    backgroundColor: COLORS.primary,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.sm,
  },
  statLabel: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: SPACING.sm,
    fontWeight: '500',
  },
  statNumber: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  chartContainer: {
    marginTop: 20, 
    marginBottom: 25,
    alignItems: 'center',
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: 10,
  },
  chart: {
    borderRadius: 16,
  },
  exportButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: BORDER_RADIUS.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: SPACING.md,
  },
  exportButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  dateTimePickerButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  noteContainer: {
    marginBottom: SPACING.md,
  },
  noteInput: {
    backgroundColor: "#252525",
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.md,
    color: COLORS.text,
    fontSize: 16,
    minHeight: 80,
    textAlignVertical: "top",
  },
  addNoteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: SPACING.sm,
    backgroundColor: "#333333",
    borderRadius: BORDER_RADIUS.sm,
    marginTop: SPACING.sm,
    marginBottom: SPACING.md,
  },
  addNoteButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "500",
  },
  formButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: SPACING.md,
  },
  formButton: {
    flex: 1,
    padding: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 4,
  },
  cancelButton: {
    backgroundColor: "#444444",
  },
  saveButton: {
    backgroundColor: COLORS.primary,
  },
  centerContent: {
    flex: 1, 
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    color: '#fff',
    marginTop: 10,
    fontSize: 16,
  },
  errorText: {
    color: '#ff6b6b', 
    marginTop: 15,
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#007BFF',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginTop: 10,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  refreshButton: {
    flexDirection: 'row',
    backgroundColor: '#28a745', 
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15, 
    marginBottom: 30, 
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  refreshButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  noDataText: {
    color: '#aaa',      // Grey color for placeholder text
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 15,
    fontStyle: 'italic',
  }
});