  import { StyleSheet } from "react-native";

  const COLORS = {
    primary: "#4A90E2",
    danger: "#E94E77",
    success: "#4CAF50",
    background: "#121212",
    text: "#FFFFFF",
    border: "#333333",
    white: "#FFFFFF",
    gray: "#888888",
    placeholder: "#AAAAAA",
  };

  const SPACING = {
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  };

  const BORDER_RADIUS = {
    sm: 4,
    md: 8,
    lg: 12,
  };

  export const styles = StyleSheet.create({

  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  activitiesContainer: {
    flex: 1,
    padding: 10,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
  cardText: {
    fontSize: 14,
    color: "#333",
    marginBottom: 3,
  },
  cardButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 5,
    alignItems: "center",
    marginHorizontal: 5,
  },
  viewButton: {
    backgroundColor: "#4CAF50",
  },
  editButton: {
    backgroundColor: "#2196F3",
  },
  deleteButton: {
    backgroundColor: "#F44336",
  },
  buttonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  addButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#2196F3",
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
  },
  addButtonText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "bold",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 20,
    width: "90%",
    maxHeight: "80%",
  },
  summaryTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  summaryDateTimeContainer: {
    marginBottom: 10,
  },
  summaryLabel: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
  },
  summaryDateTime: {
    fontSize: 14,
    color: "#333",
  },
  summaryScrollView: {
    maxHeight: 300,
  },
  summarySection: {
    marginBottom: 10,
  },
  summaryNoteContainer: {
    backgroundColor: "#f9f9f9",
    padding: 10,
    borderRadius: 5,
    marginBottom: 5,
  },
  summaryNoteText: {
    fontSize: 14,
    color: "#333",
  },
  summaryCloseButton: {
    backgroundColor: "#2196F3",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    marginBottom: 10,
    fontSize: 14,
  },
  noteContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  removeNoteButton: {
    backgroundColor: "#F44336",
    padding: 8,
    borderRadius: 5,
    marginLeft: 10,
  },
  addNoteButton: {
    backgroundColor: "#4CAF50",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginBottom: 10,
  },
  formButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  submitButton: {
    backgroundColor: "#2196F3",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    flex: 1,
    marginRight: 5,
  },
  cancelButton: {
    backgroundColor: "#F44336",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    flex: 1,
    marginLeft: 5,
  },
    container: {
      flex: 1,
      backgroundColor: COLORS.background,
    },
    activitiesContainer: {
      padding: SPACING.md,
    },
    card: {
      flexDirection: "column", // Changed from row to column
      padding: SPACING.md,
      marginBottom: SPACING.md,
      backgroundColor: "#252525",
      borderRadius: BORDER_RADIUS.md,
      borderWidth: 1,
      borderColor: COLORS.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 3,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: COLORS.text,
      marginBottom: SPACING.sm,
    },
    cardText: {
      fontSize: 14,
      color: COLORS.text,
      marginBottom: SPACING.sm,
    },
    cardButtons: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginTop: SPACING.sm,
      gap: SPACING.sm,
    },
    viewButton: {
      backgroundColor: COLORS.primary,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.sm,
      alignItems: "center",
      justifyContent: "center",
    },
    editButton: {
      backgroundColor: "#0070F3",
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.sm,
      alignItems: "center",
      justifyContent: "center",
    },
    deleteButton: {
      backgroundColor: COLORS.danger,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.sm,
      alignItems: "center",
      justifyContent: "center",
    },
    buttonText: {
      color: COLORS.white,
      fontSize: 14,
      fontWeight: "600",
    },
    addButton: {
      backgroundColor: COLORS.white,
      width: 60,
      height: 60,
      borderRadius: 30,
      alignItems: "center",
      justifyContent: "center",
      position: "absolute",
      bottom: 30,
      right: 30,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      borderWidth: 1,
      borderColor: "#E0E0E0",
    },
    addButtonText: {
      color: "#000000",
      fontSize: 24,
      fontWeight: "bold",
    },
    modalContainer: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      width: "90%",
      backgroundColor: "#1E1E1E",
      padding: SPACING.lg,
      borderRadius: BORDER_RADIUS.md,
      maxHeight: "80%",
    },
    summaryTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: COLORS.text,
      marginBottom: SPACING.md,
    },
    summaryDateTimeContainer: {
      marginBottom: SPACING.md,
    },
    summaryLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: COLORS.text,
      marginBottom: SPACING.sm,
    },
    summaryDateTime: {
      fontSize: 14,
      color: COLORS.text,
    },
    summaryScrollView: {
      maxHeight: 300,
    },
    summarySection: {
      marginBottom: SPACING.md,
    },
    summaryNoteContainer: {
      backgroundColor: "#252525",
      padding: SPACING.sm,
      borderRadius: BORDER_RADIUS.sm,
      marginBottom: SPACING.sm,
    },
    summaryNoteText: {
      fontSize: 14,
      color: COLORS.text,
    },
    summaryCloseButton: {
      backgroundColor: COLORS.primary,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.sm,
      alignItems: "center",
      marginTop: SPACING.md,
    },
    // Add these styles to your StyleSheet
  formScrollView: {
    paddingBottom: SPACING.lg,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.text,
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
  },
  input: {
    backgroundColor: "#252525",
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.md,
    color: COLORS.text,
    fontSize: 16,
  },
  pickerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  pickerContainer: {
    flex: 1,
    backgroundColor: "#252525",
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginRight: SPACING.sm,
    overflow: "hidden",
  },
  noteContainer: {
    marginBottom: SPACING.md,
  },
  noteInput: {
    backgroundColor: "#252525",
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.md,
    color: COLORS.text,
    fontSize: 16,
    minHeight: 80,
    textAlignVertical: "top",
  },
  addNoteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: SPACING.sm,
    backgroundColor: "#333333",
    borderRadius: BORDER_RADIUS.sm,
    marginTop: SPACING.sm,
    marginBottom: SPACING.md,
  },
  addNoteButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "500",
  },
  formButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: SPACING.md,
  },
  formButton: {
    flex: 1,
    padding: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 4,
  },
  cancelButton: {
    backgroundColor: "#444444",
  },
  saveButton: {
    backgroundColor: COLORS.primary,
  },
  });