import { StyleSheet } from "react-native";

const COLORS = {
  primary: "#4A90E2",
  danger: "#E94E77",
  success: "#4CAF50",
  background: "#121212",
  text: "#FFFFFF",
  border: "#333333",
  white: "#FFFFFF",
  gray: "#888888",
  placeholder: "#AAAAAA",
};

const SPACING = {
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
};

const BORDER_RADIUS = {
  sm: 4,
  md: 8,
  lg: 12,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: "relative",
    backgroundColor: COLORS.background,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "90%",
    backgroundColor: "#1E1E1E",
    padding: 20,
    borderRadius: 10,
    maxHeight: "80%",
  },
  formScrollView: {
    paddingBottom: 20,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 8,
    marginTop: 12,
  },
  input: {
    backgroundColor: "#252525",
    borderWidth: 1,
    borderColor: "#333333",
    borderRadius: 5,
    padding: 12,
    fontSize: 16,
    color: "#FFFFFF",
    marginBottom: 15,
    placeholderTextColor: COLORS.placeholder,
  },
  pickerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  pickerContainer: {
    flex: 1,
    marginHorizontal: 4,
    backgroundColor: "#252525",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#333333",
    overflow: "hidden",
  },
  pickerItem: {
    color: "#FFFFFF",
  },
  noteContainer: {
    marginBottom: 10,
  },
  noteInput: {
    backgroundColor: "#252525",
    borderWidth: 1,
    borderColor: "#333333",
    borderRadius: 5,
    padding: 12,
    fontSize: 14,
    color: "#FFFFFF",
    minHeight: 50,
    textAlignVertical: "top",
    placeholderTextColor: COLORS.placeholder,
  },
  addNoteButton: {
    backgroundColor: "#0070F3",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
  },
  addNoteButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  formButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  formButton: {
    flex: 1,
    padding: 12,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButton: {
    backgroundColor: "#0070F3",
    marginLeft: 10,
  },
  cancelButton: {
    backgroundColor: "#FF1A1A",
    marginRight: 10,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  notesSection: {
    marginTop: SPACING.lg,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.text,
    marginBottom: SPACING.md,
  },
  addButton: {
    backgroundColor: "#FFFFFF",
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: 30,
    right: 30,
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  addButtonText: {
    color: "#000000",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 2,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  removeButton: {
    marginLeft: SPACING.sm,
    backgroundColor: COLORS.danger,
    borderRadius: BORDER_RADIUS.sm,
    padding: SPACING.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  removeButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold",
  },
  checklistContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#252525",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.sm,
    marginBottom: SPACING.md,
  },
  checklistInput: {
    flex: 1,
    fontSize: 14,
    color: COLORS.text,
    paddingHorizontal: SPACING.sm,
    placeholderTextColor: COLORS.placeholder,
  },
  checklistToggle: {
    marginLeft: SPACING.sm,
  },
  checkboxText: {
    fontSize: 16,
    color: COLORS.gray,
  },
  completed: {
    textDecorationLine: "line-through",
    color: COLORS.success,
  },
  activitiesContainer: {
    marginTop: 20,
    paddingHorizontal: 16,
  },
  activitiesTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.text,
    marginBottom: 10,
  },
  activitiesList: {
    maxHeight: 300,
  },
  activityItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 8,
    backgroundColor: "#252525",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  activityName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
    flex: 1,
  },
  activityTime: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.primary,
    marginLeft: 16,
  },
});